Portfolio: setup and mobile version skeleton
Brenda309/Personal-portfolio pull request #1
Opened 2022-02-16 22:41 UTC by Brenda309

### In this pull request, I:

- [x] created the toolbar
- [x] created the headline section

2022-02-16 23:54 UTC, keroloussamy requested changes
Hi @Brenda309, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 23:54 UTC, keroloussamy commented on style.css
> +}
- [ ] Kindly change the font for this paragraph to make it like the Figma design.

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35535130/154376561-c952cb8e-8641-4a61-a44e-94d61bdf419f.png) | ![image](https://user-images.githubusercontent.com/35535130/154376611-3ffba849-aea1-4451-941e-57104eb3855c.png) |

2022-02-16 23:54 UTC, keroloussamy commented on style.css
> +}
- [ ] Kindly change the font for this `h2` to make it like the Figma design and the color and remove the underline.

| Your design  | Figma design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35535130/154376865-74ecad34-f6ea-43d9-8252-206c3cd17dce.png) | ![image](https://user-images.githubusercontent.com/35535130/154376819-433f6bf9-500e-4a66-867e-3590dee85967.png) |

2022-02-16 23:54 UTC, keroloussamy commented on README.md
> +- LinkedIn: [Wihogora Brenda](https://linkedin.com/in/linkedinhandle)
- [ ] Kindly change the link to your actual link, so anyone can contact you.

Like
- GitHub: `[Brenda309](https://github.com/Brenda309)`

2022-02-16 23:54 UTC, keroloussamy commented on README.md
- [ ] Kindly change this title to the project name.

2022-02-17 19:06 UTC, nicupop729 requested changes
# Status: Required Changes ♻️

Hi @Brenda309, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)

 ### Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [x] In future let's make sure we use descriptive commit messages - each commit should be small enough to describe it in one sentence. The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8).
Your commit messages are repetitive, are not capitalized and are not descriptive. You cannot change them now, but please consider writing more meaningful commit messages from now on.
- [x] The name of your portfolio is at the moment "mobile-portfolio", but next week we will make it responsive and it will adapt to desktop view as well. Because of this, you can consider renaming your project something more meaningful. As simple as "Portfolio" or "Personal Portfolio" will do. If you rename it, don't forget to edit your README as too.
- [ ] Please consider adding `.gitignore` file to your repo and in that file, add `node_modules/`.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-17 21:32 UTC, merged